name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Building and Uploading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 8
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install
      - run: pnpm build
      - run: mv dist websdk
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: websdk
          container_name: websdk
          account_name: telemetrydeckcdn
          sas_token: ${{ secrets.CDN_AZURE_SAS_TOKEN }}
          overwrite: 'true'
